// User Actions
export const LOAD_CONTRIBUTORS_SUCCESS = "LOAD COURSES_SUCCESS";

export const FILTER_CONTRIBUTORS_BY_LESS_CONTRIBUTIONS =
  "FILTER_CONTRIBUTORS_BY_LESS_CONTRIBUTIONS";

export const FILTER_CONTRIBUTORS_BY_MORE_CONTRIBUTIONS =
  "FILTER_CONTRIBUTORS_BY_MORE_CONTRIBUTIONS";

export const FILTER_CONTRIBUTORS_BY_ASCENDING_NAME =
  "FILTER_CONTRIBUTORS_BY_ASCENDING_NAME";

export const FILTER_CONTRIBUTORS_BY_DESCENDING_NAME =
  "FILTER_CONTRIBUTORS_BY_DESCENDING_NAME";

// API Status Actions
export const API_CALL_ERROR = "API_CALL_ERROR";

// Common Actions
export const LOADING = "LOADING";
export const NO_LOADING = "NO_LOADING";
