// User Actions
export const LOAD_CONTRIBUTORS_SUCCESS = "LOAD COURSES_SUCCESS";
export const FILTER_CONTRIBUTORS_BY_DESCENDING_CONTRIBUTIONS =
  "FILTER_CONTRIBUTORS_BY_DESCENDING_CONTRIBUTIONS";

// API Status Actions
export const API_CALL_ERROR = "API_CALL_ERROR";

// Common Actions
export const LOADING = "LOADING";
export const NO_LOADING = "NO_LOADING";
